# Site settings
title: Bolded.org
email: team@bolded.org
description: > # this means to ignore newlines until "baseurl:"
  Bolded aims to become eastern hemisphere’s biggest force in advocating corporations to hire more underprivileged people. Hongkong and Philippines are the project’s launch regions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bolded.org" # the base hostname & protocol for your site
twitter_username: bolded

# Build settings
markdown: kramdown
